name: Trigger auto deployment for springpetclinicrpza

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/springpetclinicrpza-AutoDeployTrigger-c25af6c2-6543-46e4-93f4-58f02ef876e9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'microsoft'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: springpetclinicrpza.azurecr.io
          username: ${{ secrets.SPRINGPETCLINICRPZA_REGISTRY_USERNAME }}
          password: ${{ secrets.SPRINGPETCLINICRPZA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: springpetclinicrpza.azurecr.io/springpetclinic:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGPETCLINICRPZA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n springpetclinicrpza -g springpetclinicrzpa --server springpetclinicrpza.azurecr.io --username  ${{ secrets.SPRINGPETCLINICRPZA_REGISTRY_USERNAME }} --password ${{ secrets.SPRINGPETCLINICRPZA_REGISTRY_PASSWORD }}
            az containerapp update -n springpetclinicrpza -g springpetclinicrzpa --image springpetclinicrpza.azurecr.io/springpetclinic:${{ github.sha }}
